### PR TITLE
scanRigAddon improvements for management on dome shape and render 

### PR DESCRIPTION
**Pull request by ejurquet**
This is a scanRiggAddon revision and upgrade to simplify management on dome shape and render.
This work was carried out as part of an internship at the Toulouse Computer Science Research Institute (IRIT) under the supervision of @simogasp   and Remy Alcouffe, during my 2nd year of computer engineering studies at ENSEEIHT.

The changes made are as follows :
- Added **dome shape** and **size** management. The dome has now 3 different configurations:
  - `sphere` (as it was previously) in which the dome is simulated placing the cameras on an arc of circumference that rotates around the axis. This provides an uneven distribution of the cameras on the sphere surface (I.e. more dense cameras on the poles than the equator)
  - `icosahedron` in which the cameras are placed on the vertices of an icosahedron. This better samples the surface of the sphere. It is possible to change the number of cameras of the dome by setting the subdivision steps of the icosahedron, the larger the step the higher the number of cameras. (i.e. 12 cameras for step 1, 42 cameras for step 2 and so on)
  - `UV sphere` similar to the first option but with all cameras put in place on the surface of a sphere instead of a moving arc of circumference.
- Added rendering options for generating **depth**, **normal**, **albedo** and **id** map using Blender nodes (based on the stanford shapenet renderer script: https://github.com/panmari/stanford-shapenet-renderer).
image

- Updated add-on menu UI for parameters.
- Created an `__init__.py` script to manage dependencies and simplify installation.
- Updated README file accordingly.
- Added a TODO for listing possible future improvement.

Tested versions : Blender 2.93 and 3.0.

### CODE REVIEW

**Comment by ralcouff** [comment]
Hi @ejurquet,
The parameter  "Camera Distance" (after clicking the "Setup the scene button") is only used in the Sphere configuration, but it is displayed in all the configurations. We could only display it in the Sphere configuration and the Slice Camera Management.

**Comment by ejurquet** [comment]
Hi @ralcouff,
The parameter should now only be displayed in the Slice Camera Management section of the Sphere Configuration panel.
Let me know if you encounter any other issues.
Thank you.

**Comment by ralcouff** [comment]
Hi @ejurquet 
I've tried other things and when updating to Blender 3.0, the parameter tile_x of the RenderSettings object no longer exists. You can maybe make an if / else statement on the blender version for this parameter ?
The error occurs when i click the "Set Project Settings" button, I have 
`scanRigAddon.py", line 127, in execute
  rdr.tile_x = self.tileSize
AttributeError: 'RenderSettings' object has no attribute 'tile_x'
`

**Comment by ejurquet** [comment]
Hello again @ralcouff,
I pushed an if / else statement on the blender version in consequence.
Now, if the version is older than 3.0.0, we don't activate nor display the tileSize management.
I will look for other parameters than tile_x and tile_y that could be used in the 3.0.0 version.
Thank you 🙂

**Comment by hdgnd** [comment]
Hello Eliès!
I am one of the primary developers of `ScanRig`. Thank you very much for your contribution improving this little `Blender` tool.
Actually, at first, it was only a way for us to get a preview of what our real setup would look like. It is cool to see it can be used for deeper usage!

I have tested your implementation with `Blender-2.93.7`, and here are the feedbacks I can give you.

- This is very cool to give a choice for the structural disposition of cameras in space. As you wrote in the `readme`, the "Photometry Management" part is only effective for the `Sphere` structure so I think it would be nice if those properties were displayed only with this option, to avoid ghost parameters. This is also true for the `Render mode` since the photometry is only available with `Sphere` structure.
- On your PR description, you use the term "arc of circumference that rotates around the axis". I think it would be more explicit if the `Sphere` structure name was replaced by something like `Arc` or `Spinning Arc`.
- With the `Sphere` structure, I tried to render some photometry images and the result was the same for all the directions. I did not investigate more but there is maybe an issue somewhere.
- The `dome distance` works well! However, you should take it in count for the lighting power 😉 My renders were full black at first because the lights were too far from my object.
- I do not know how the `id` pass works but the renders were all black. Was I supposed to enable anything before launching the render?
- I think `Beauty` is a better name for the "composited" pass than `Basic`. I am not 100% sure of the term but I guess this is the good one.
- And the last, but not the least, I did not deep dive into the code but as far as I know, you did not append your name to the addon "authors" property!! Why so? You are a contributor as much as we are, now! 😄 

This was my little review of the tool (on the user side)! Great job!

If you have questions about the code itself, do not hesitate 🙂

Julien

**Pull request merged**
